version: "3.7"
services:
  db:
    restart: always
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: calcpass
      MYSQL_DATABASE: Calculator
      TZ: America/Guatemala
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
  frontend:
    restart: always
    image: erwin14k/frontend_practica1_202001534:1.00
    ports:
      - "3000:3000"
  backend:
    restart: always
    image: erwin14k/backend_practica1_202001534:1.00
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - logs_volume:/app/Backend
  linux_container:
    restart: always
    image: erwin14k/script_practica1_202001534:1.00
    environment:
      TZ: America/Guatemala
    volumes:
      - logs_volume:/app/Backend
    working_dir: /app/Backend
volumes:
  db-data:
  logs_volume:
