version: "3.7"
services:
  db:
    restart: always
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: calcpass
      MYSQL_DATABASE: Calculator
      TZ: America/Guatemala
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
  frontend:
    restart: always
    image: erwin14k/calculator-front-end:1.00
    ports:
      - "3000:3000"
  backend:
    restart: always
    image: erwin14k/calculator_back_end:1.00
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - logs_volume:/app/Backend
      #- ./calculator-back-end/reportsScript.sh:/app/Backend/reportsScript.sh
  linux_container:
    restart: always
    image: bash:5.2.15-alpine3.16
    environment:
      TZ: America/Guatemala
    volumes:
      - logs_volume:/app/Backend
    working_dir: /app/Backend
    stdin_open: true
    tty: true
volumes:
  db-data:
  logs_volume:
